### ISSUE TITLE
Gemini executable doesn't seem to do anything

### ISSUE THREAD

**Issue by yurivict** [blooser/gemini#1]
I've built it on FreeBSD. But it just hangs, and doesn't do anything.
Only one file gets installed.

**Comment by blooser** [comment]
Hi!

Can you check your Qt version with `qtdiag`? I think one of the Qt's module requires >=5.11.

I will make required Qt version by gemini and update all needed packages.

**Comment by blooser** [comment]
I restored [error output](https://github.com/blooser/gemini/commit/5c2c1d53705ee88137cab8f59d71062b517c6d73) it should show what went wrong with the build.

It can be QtQuick modules missing, try to upgrade or install modules with `Qt Maintenance Tools`.
